//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentWrapper.Services {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Appsetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static Appsetting defaultInstance = ((Appsetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Appsetting())));
        
        public static Appsetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sandbox.monnify.com/")]
        public string Monnify_BaseUrl_Test {
            get {
                return ((string)(this["Monnify_BaseUrl_Test"]));
            }
            set {
                this["Monnify_BaseUrl_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sandbox.monnify.com/")]
        public string Monnify_BaseUrl_Production {
            get {
                return ((string)(this["Monnify_BaseUrl_Production"]));
            }
            set {
                this["Monnify_BaseUrl_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool User_Production_Credentails {
            get {
                return ((bool)(this["User_Production_Credentails"]));
            }
            set {
                this["User_Production_Credentails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/v1/merchant/transactions/init-transaction")]
        public string Monnify_NewTransaction_Test {
            get {
                return ((string)(this["Monnify_NewTransaction_Test"]));
            }
            set {
                this["Monnify_NewTransaction_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/v1/merchant/transactions/init-transaction")]
        public string Monnify_NewTransaction_Production {
            get {
                return ((string)(this["Monnify_NewTransaction_Production"]));
            }
            set {
                this["Monnify_NewTransaction_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/v2/transactions/")]
        public string Monnify_Requery_Test {
            get {
                return ((string)(this["Monnify_Requery_Test"]));
            }
            set {
                this["Monnify_Requery_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/v2/transactions/")]
        public string Monnify_Requery_Production {
            get {
                return ((string)(this["Monnify_Requery_Production"]));
            }
            set {
                this["Monnify_Requery_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NGN")]
        public string Monnify_Current {
            get {
                return ((string)(this["Monnify_Current"]));
            }
            set {
                this["Monnify_Current"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.paystack.co/")]
        public string Paystack_BaseUrl_Test {
            get {
                return ((string)(this["Paystack_BaseUrl_Test"]));
            }
            set {
                this["Paystack_BaseUrl_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.paystack.co/")]
        public string Paystack_BaseUrl_Production {
            get {
                return ((string)(this["Paystack_BaseUrl_Production"]));
            }
            set {
                this["Paystack_BaseUrl_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transaction/initialize")]
        public string Paystack_InitializeTransaction_Url_Production {
            get {
                return ((string)(this["Paystack_InitializeTransaction_Url_Production"]));
            }
            set {
                this["Paystack_InitializeTransaction_Url_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transaction/verify/{0}")]
        public string Paystack_VerifyTransaction_Url_Test {
            get {
                return ((string)(this["Paystack_VerifyTransaction_Url_Test"]));
            }
            set {
                this["Paystack_VerifyTransaction_Url_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transaction/verify/{0}")]
        public string Paystack_VerifyTransaction_Url_Production {
            get {
                return ((string)(this["Paystack_VerifyTransaction_Url_Production"]));
            }
            set {
                this["Paystack_VerifyTransaction_Url_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://remitademo.net/remita/exapp/api/v1/send/api/echannelsvc/merchant/api/paym" +
            "entinit")]
        public string Remita_paymentinit_url_Test {
            get {
                return ((string)(this["Remita_paymentinit_url_Test"]));
            }
            set {
                this["Remita_paymentinit_url_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.remita.net/remita/exapp/api/v1/send/api/echannelsvc/merchant/api/pa" +
            "ymentinit")]
        public string Remita_paymentinit_url_Production {
            get {
                return ((string)(this["Remita_paymentinit_url_Production"]));
            }
            set {
                this["Remita_paymentinit_url_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.remitademo.net/remita/ecomm")]
        public string Remita_Check_Status_Url_Test {
            get {
                return ((string)(this["Remita_Check_Status_Url_Test"]));
            }
            set {
                this["Remita_Check_Status_Url_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://login.remita.net/remita/ecomm")]
        public string Remita_Check_Status_Url_Production {
            get {
                return ((string)(this["Remita_Check_Status_Url_Production"]));
            }
            set {
                this["Remita_Check_Status_Url_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.flutterwave.com/v3/transactions/{0}/verify")]
        public string Fluttter_FlutterRequeryURL_Test {
            get {
                return ((string)(this["Fluttter_FlutterRequeryURL_Test"]));
            }
            set {
                this["Fluttter_FlutterRequeryURL_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.flutterwave.com/v3/payments")]
        public string Fluttter_FlutterWavePaymentURL_Test {
            get {
                return ((string)(this["Fluttter_FlutterWavePaymentURL_Test"]));
            }
            set {
                this["Fluttter_FlutterWavePaymentURL_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.flutterwave.com/v3/transactions/{0}/verify")]
        public string Fluttter_FlutterRequeryURL_Production {
            get {
                return ((string)(this["Fluttter_FlutterRequeryURL_Production"]));
            }
            set {
                this["Fluttter_FlutterRequeryURL_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.flutterwave.com/v3/payments")]
        public string Fluttter_FlutterWavePaymentURL_Production {
            get {
                return ((string)(this["Fluttter_FlutterWavePaymentURL_Production"]));
            }
            set {
                this["Fluttter_FlutterWavePaymentURL_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/v1/auth/login")]
        public string Monnify_Auth_Production {
            get {
                return ((string)(this["Monnify_Auth_Production"]));
            }
            set {
                this["Monnify_Auth_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/v1/auth/login")]
        public string Monnify_Auth_Test {
            get {
                return ((string)(this["Monnify_Auth_Test"]));
            }
            set {
                this["Monnify_Auth_Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transaction/initialize")]
        public string Paystack_InitializeTransaction_Url_Test {
            get {
                return ((string)(this["Paystack_InitializeTransaction_Url_Test"]));
            }
            set {
                this["Paystack_InitializeTransaction_Url_Test"] = value;
            }
        }
    }
}
